[package]
name = "vos-hardware"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vos-core.workspace = true
vos-cpu.workspace = true
vos-memory.workspace = true
vos-io.workspace = true
serde.workspace = true

[dev-dependencies]
